#! /bin/bash

#cat /home/aamonm/Programming/AamonDwm/options.txt | dmenu -fn "monospace:size=12" -nb "#222222" -nf "#bbbbbb" -sb "#ff00ff" -sf "#000000" -l 50
cat ~/Programming/AamonDwm/keybindings.txt | dmenu -fn "monospace:size=10" -l 50 -i -c -p "Keybindings:"
