#!/usr/bin/env bash

prompt="-p Path:"
root_path="$HOME"

find_path="$(find $root_path -maxdepth 3 -type d | \
             sed 's|^'$root_path/'||' | \
             dmenu -i $prompt -c -l 20)"

if [[ ! -z "$find_path" ]]; then
   alacritty -e ranger "$HOME/$find_path" &
fi

exit 0
