#! /bin/bash

options="Shutdown\nRestart\nSleep"

choice=$(echo -e "$options" | dmenu -c -i -l 5)

case "$choice" in
	Shutdown) /home/aamonm/Programming/AamonDwm/shutdown-dmenu;;
	Restart) /home/aamonm/Programming/AamonDwm/restart-dmenu;;
	Sleep) slock;;
esac
