#!/usr/bin/env bash

script_path="$HOME/Programming/AamonDwm"

prompt="-p DmenuMenu:"

# list only executable non-binay files

run_dmenu="$(find $script_path/dmenu-* -maxdepth 1 -type f -executable \
          -exec grep -Iq . {} \; -print \
          | sed 's|^'$script_path/'||' \
          | sort \
          | dmenu $prompt -c -l 20)"

eval "$script_path/$run_dmenu"

exit 0
