#! /bin/bash

mount(){
	mountable=$(lsblk -lp | grep "part $" | grep -v "nvme" | awk '{print $1, "(" $4 ")"}')
	[[ "$mountable" = "" ]] && exit 0
	chosen=$(echo "$mountable" | dmenu -i -p "Mount which drive?" | awk '{print $1}')
	[[ "$chosen" = "" ]] && exit 0

	dirs=$(find /run/media/$USER -type d -maxdepth 3 2> /dev/null)
	mountpoint=$(echo "$dirs" | dmenu -i -p "Pick mount point" )
	[[ "$mountpoint" = "" ]] && exit 0

	if [[ ! -d "$mountpoint" ]]; then
		mkdiryn=$(echo -e "No\nYes" | dmenu -i -p "$mountpoint does not exist. Create it?")
		[[ "$mkdiryn" = "Yes" ]] && sudo mkdir -p "$mountpoint"
	fi

	sudo mount "$chosen" $mountpoint > /dev/null
}

unmount(){
	exclusionregex="\(/boot\|/home\|/\)$"
	drives=$(lsblk -lp | grep "t /" | grep -v "$exclusionregex" | awk '{print $1, "(" $4 ")", "on", $7}')
	[[ "$drives" = "" ]] && exit 0
	chosen=$(echo "$drives" | dmenu -i -p "Unmount which drive?" | awk '{print $1}')
	[[ "$chosen" = "" ]] && exit 0
	sudo umount $chosen
}

mode=$(echo -e "mount\nunmount" | dmenu -i -p "Select mode")

case "$mode" in
	mount) mount ;;
	unmount) unmount ;;
esac
