#! /bin/bash

programs="alacritty\ngoogle-chrome-stable\npcmanfm\nlibreoffice\nranger\ngtop\ndiscord\nlxappearance\nfirefox"

choice=$( echo -e "$programs" | sort | dmenu -p "Prefered Programs" )

if [ $choice == "ranger" ]; then
	alacritty -e ranger
elif [ $choice == gtop ]; then
	alacritty -e gtop
else
	eval $choice
fi
