#! /bin/bash

places="CurrentLocation\nCalgary\nVancouver\nSundre\nRocanville\nQuebec\nWinnipeg"

choice=$( echo -e $places | dmenu -i -p "Weather" )

path="$HOME/.weather/$choice.weather"

if [ ! $choice ]; then
	exit 0
fi

if [[ $choice == "CurrentLocation" ]]; then
	curl wttr.in > $path
else
	curl wttr.in/$choice > $path
fi

xdotool key Super_L+m
st -e less -Srf ~/.weather/$choice.weather
xdotool key Super_L+t
