#! /bin/bash

mount(){
	mountable=$(lsblk -lp | grep "part $" | grep -v "nvme" | awk '{print $1, "(" $4 ")"}')
	[[ "$mountable" = "" ]] && exit 0
	size=$(echo $mountable | awk '{print $2}')
	chosen=$(echo "$mountable" | dmenu -i -p "Mount which drive?" | awk '{print $1}')
	[[ "$chosen" = "" ]] && exit 0

	dirs="LargeDrive\nSmallDrive\nUsbDrive"
	label=$(echo -e "$dirs" | dmenu -i -p "Label mount point" )
	[[ "$label" = "" ]] && exit 0

	mountpoint="/run/media/$USER/$label"

	if [[ ! -d "$mountpoint" ]]; then
		mkdiryn=$(echo -e "Yes\nNo" | dmenu -i -p "$mountpoint does not exist. Create it?")
		[[ "$mkdiryn" = "Yes" ]] && SUDO_ASKPASS=/usr/AamonDwmScripts/sudo_dmenu sudo mkdir -p "$mountpoint"
	fi

	# alacritty -e sudo mount "$chosen" $mountpoint > /dev/null
	SUDO_ASKPASS=/usr/AamonDwmScripts/sudo_dmenu sudo -A mount "$chosen" $mountpoint > /dev/null && notify-send "USB mounted to $mountpoint $size"
}

unmount(){
	exclusionregex="\(/boot\|/home\|/\)$"
	drives=$(lsblk -lp | grep "t /" | grep -v "$exclusionregex" | awk '{print $1, "(" $4 ")", "on", $7}')
	[[ "$drives" = "" ]] && exit 0
	mountpoint=$(echo $drives | awk '{print $4}')
	size=$(echo $drives | awk '{print $2}')
	chosen=$(echo "$drives" | dmenu -i -p "Unmount which drive?" | awk '{print $1}')
	[[ "$chosen" = "" ]] && exit 0
	# alacritty -e sudo umount $chosen
	SUDO_ASKPASS=/usr/AamonDwmScripts/sudo_dmenu sudo -A umount $chosen && notify-send "USB unmounted from $mountpoint $size"
}

mode=$(echo -e "mount\nunmount" | dmenu -i -p "Select mode")

case "$mode" in
	mount) mount ;;
	unmount) unmount ;;
esac
