#!/usr/bin/env bash

script_path="/usr/AamonDwmScripts"

prompt="-p DmenuMenu:"

# list only executable non-binay files

run_dmenu="$(find $script_path/dmenu-* -maxdepth 1 -type f -executable \
          -exec grep -Iq . {} \; -print \
          | sed 's|^'$script_path/dmenu-'||' \
          | sort \
          | dmenu $prompt)"

$( "$script_path/dmenu-$run_dmenu" )

exit 0
